### ISSUE TITLE
range end index 8263 out of range for slice of length 1024

### ISSUE THREAD

**Issue by diondokter** [tweedegolf/nvm-log#6]
https://github.com/tweedegolf/nvm-log/blob/83ceb9fdc9a68b7a51c6f281ceb4209ef5c88ac8/src/lib.rs#L502

**Comment by hdoordt** [comment]
Error message
```
5.732788 Panic: panicked at 'range end index 8263 out of range for slice of length 1024', [redacted]/.cargo/git/checkouts/nvm-log-5facbc5284712a63/83ceb9f/src/lib.rs:502:54
└─ [redacted]::panic @ src/main.rs:1136
```

Seemingly another case: 'slice index starts at 1 but ends at 0`

```
4.616729 Panic: panicked at 'slice index starts at 1 but ends at 0', [redacted].cargo/git/checkouts/nvm-log-5facbc5284712a63/83ceb9f/src/lib.rs:502:54
└─ [redacted]::panic @ src/main.rs:1139
────────────────────────────────────────────────────────────────────────────────
Error: An ARM specific error occured.

```
